Clean up + fix build
Previous builds failed because the TestTarget effectors used rtxSignal()
to raise a signal not defined in the test model and not checked in the
runtime.

Changes to fix this:
- dump log file if ribose run|compile fail
- dump compile and run logs at end of ci builds
- move IEffector.rtxSignal(int) to IOutput.signal(int)
- implement as Transductor.signal(int)
- update IEffector implementations to use IOutput.signal()
- fix up javadoc comments referring to IEffector.rtxSignal()
- clean up ValuesTest.inr

Changes from reverted commits (included in this commit):
- drop IField.decodeValue()
  - use IField.asString() (equivalent to IField.toString())
- drop Model.writeBytes(Bytes)
  - use Model.writeBytes(Bytes.bytes())
- Transductor loops on matchMode
- add .data to .gitignore

Signed-off-by: jrte <jrte.project@gmail.com>

diff --git a/ribose b/ribose
--- a/ribose
+++ b/ribose
@@ -6,6 +6,11 @@ execRun() {
 		shift
 	fi
 	$JAVA -ea -cp $path $vmargs com.characterforming.ribose.Ribose run $nil "$@"
+	rc=$?
+	if ((rc!=0)); then
+		echo "Run failed with exit code $rc"; cat ./ribose-runtime-0.log
+	fi
+	return $rc
 }
 
 execCompile() {
@@ -20,6 +25,11 @@ execCompile() {
 	else
 		$JAVA -ea -cp $path $vmargs com.characterforming.ribose.Ribose compile --target com.characterforming.jrte.engine.SimpleTarget "$@"
 	fi
+	rc=$?
+	if ((rc!=0)); then
+		echo "Compile failed with exit code $rc"; cat ./ribose-compile-0.log
+	fi
+	return $rc
 }
 
 execDecompile() {
