Debug failed CI build
- dump log output if task fails

Signed-off-by: jrte <jrte.project@gmail.com>

diff --git a/ribose b/ribose
--- a/ribose
+++ b/ribose
@@ -6,6 +6,7 @@ execRun() {
 		shift
 	fi
 	$JAVA -ea -cp $path $vmargs com.characterforming.ribose.Ribose run $nil "$@"
+	rc=$?; if (($rc!=0)); then echo "Task failed with exit code $rc"; cat ./ribose-runtime-0.log; exit $rc; fi
 }
 
 execCompile() {
@@ -20,6 +21,7 @@ execCompile() {
 	else
 		$JAVA -ea -cp $path $vmargs com.characterforming.ribose.Ribose compile --target com.characterforming.jrte.engine.SimpleTarget "$@"
 	fi
+	rc=$?; if (($rc!=0)); then echo "Task failed with exit code $rc"; cat ./ribose-compile-0.log; exit $rc; fi
 }
 
 execDecompile() {
